- .travis.yml
- cextern/astrometry.net/healpix.c
- healpix/core.py
- healpix/core_cython.pyx
- healpix/healpy.py
- healpix/tests/test_core_cython.py
This improves performance by a factor of a few for ring indexing by re-writing ``hp_decompose_ring`` in closed form (without loops). We are still 3-4x slower than healpy/HEALPIX for both ring and nested indexing.
EDIT: looks like the re-write isn't quite 64-bit int compatible yet.
> Improve performance

- docs/healpy_compat.rst
- healpix/healpy.py
This PR adds minimal docstrings to the functions in `healpix.healpy`, linking to the equivalent function in `healpy`. I think this is very useful, for quick checking if the functions really are equivalent in signature or not. Plus they have good docstrings, so no need to duplicate those in our docs.
I also added a `Migrate` section to the `healpy` docs page, that mentions that one can do the one-line import change to `from healpix import healpy to hp`.
@astrofrog - Please review.
> Add docstrings to healpy interface functions

- healpix/high_level.py
@astrofrog - Here you're passing as forth argument `self.nside`, but I think it should be `approximate`, no?
https://github.com/cdeil/healpix/blob/a3cfdef81ee9d82c650ca9982cfd60897f2c12b7/healpix/high_level.py#L331
Would it be easy for you to fix and add a test case or should I do it?
> Bug in cone_search_skycoord

- .gitignore
- healpix/core.py
- healpix/core_cython.pyx
- healpix/high_level.py
- healpix/tests/test_core.py
- healpix/tests/test_high_level.py
- setup.py
This PR improves argument validation for `order` a little bit, avoiding the many duplications of `ORDER[order.lower()]`.
I also changed the language from "should" to "must" in the errors, and would suggest to do this change for all the errors in this PR. @astrofrog - OK?
The main question here I think is whether we should call `.lower` and support `order='RING'` in addition to `order='ring'`? On the one hand I think being strict it better, because it means that there's one way to do it instead of a few and all scripts calling this will look the same. On the other hand, there might be a reason to support multiple capitalisations here? If there isn't a strong one, I'm +1 to be strict.
@astrofrog - Thoughts?
> Improve order argument validation a bit

- .run_docker_tests.sh
- .travis.yml
- appveyor.yml
- docs/cone_search.rst
- docs/coordinates.rst
- healpix/core.py
- healpix/core_cython.pyx
- healpix/healpy.py
- healpix/tests/test_core.py
- healpix/tests/test_core_cython.py
- healpix/tests/test_healpy.py
- setup.py
@cdeil - I had a bit of time so worked on this. I have not done anything for the functions that get neighbours or boundaries since those already return 2D arrays, so I thought it might be confusing if we return e.g. an (8, 3, 2) array (where 8 is the number of neighbours). What do you think?
Fixes https://github.com/cdeil/healpix/issues/21
> Preserve shape of arrays in core Python functions

- .travis.yml
Now that this is fixed in astropy we can run the full tests for that build. Also I think things may actually have worked with Python 2, so trying to re-enable those.
> Skip doctests on fewer builds

- healpix/core.py
- healpix/core_cython.pyx
- healpix/high_level.py
- healpix/tests/test_core_cython.py
During investigations in https://github.com/cdeil/healpix/issues/41 I found that the approximate mode produces strange results, so I don't think we should expose it through the API. We could in future implement a mode equivalent to the one in healpy that uses just the center of the pixels, but that can be done without the C code.
> Remove approximate mode from cone search and clarify docstrings

- .gitignore
- .run_docker_tests.sh
- .travis.yml
- appveyor.yml
- healpix/tests/six.py
- healpix/tests/test_core.py
- healpix/tests/test_healpy.py
- setup.py
While updating the install page in #47 I noticed that to be complete we should mention the dependency on six. But then I looked and all we need in `integer_types` in the tests. So I'd suggest to just avoid the dependency -> this PR.
@astrofrog - thoughts?
> Do the six ourselves

- healpix/bench.py
@astrofrog - Here's a first version version of the simple benchmark tool I was suggesting we add in #22 . I don't have much time to work on it, i.e. to implement a good set of benchmarks / discuss the most useful / common ranges of parameters. Note that this is not mentioned in the docs at the moment, so it doesn't hurt to add this and continue with this at a later time.
But of course, I can improve what's here a bit, so @astrofrog - please review.
This is what I get: our `pix2ang` is 3 to 30 times slower than healpy:
```
$ python -m healpix.bench
fct   nside    size      time_healpy        time_self         ratio    
------- ----- --------- ----------------- ----------------- -------------
pix2ang     1      10.0 1.64522665087e-05 0.000443432048894 26.9526419755
pix2ang   128      10.0 …
```
> Add initial version of healpix/bench.py

- astropy_healpix/bench.py
- astropy_healpix/tests/test_bench.py
@cdeil - this implements what I was suggesting in https://github.com/astropy/astropy-healpix/issues/22#issuecomment-333340017 - namely a 'fast' mode to just make sure the benchmarks run, which is then used in testing. This flag could also be used for example to skip larger array sizes if we decide to add some.
Note that I also made it so the benchmarks do run even if healpy is not installed - this is to be absolutely in the clear license-wise and make healpy as optional as possible (i.e nothing breaks if it's not installed). Here's a run without healpy:
```
Running benchmarks...
fct   nside   size  time_self 
------- ----- ------- ----------
pix2ang     1      10  0.0010800
pix2ang   128      10  0.0004873
pix2ang     1    1000  0.0005073
pix2ang   128    1000  0.0004769
pix2ang     1 …
```
> Add fast mode for running benchmarks (used for testing)

- .gitmodules
- .run_docker_tests.sh
- CHANGES.rst
- astropy_healpix/bench.py
- astropy_healpix/conftest.py
- astropy_healpix/core_cython.pxd
- astropy_healpix/core_cython.pyx
- astropy_healpix/setup_package.py
- docs/index.rst
- docs/performance.rst
This is a WIP, but it seems to work:
**Without OpenMP compilation flags**
```
fct    nest nside   size  time_healpy time_self   ratio 
------- ----- ----- ------- ----------- ---------- -------
pix2ang  True     1      10   0.0000133  0.0004341   32.70
pix2ang  True   128      10   0.0000100  0.0003775   37.76
pix2ang  True     1    1000   0.0000521  0.0005752   11.04
pix2ang  True   128    1000   0.0000386  0.0006398   16.56
pix2ang  True     1 1000000   0.0364820  0.1662130    4.56
pix2ang  True   128 1000000   0.0316353  0.1336160    4.22
pix2ang False     1      10   0.0000151  0.0005352   35.45
pix2ang False   128      10   0.0000124  0.0004764   38.47
pix2ang False     1    1000   0.0000462  0.0005917   12.82
pix2ang False   128    1000   0.0000592  0.0006090   10.29
pix2ang False …
```
> Use OpenMP in Cython wrappers

- CHANGES.rst
- astropy_healpix/core.py
- astropy_healpix/core_cython.pyx
- astropy_healpix/high_level.py
- astropy_healpix/tests/test_core.py
- astropy_healpix/tests/test_core_cython.py
- astropy_healpix/tests/test_high_level.py
Fixes #52 - also renames the function and method to simply 'neighbors' since the ``healpix_`` is not meaningful here (we don't have it for e.g interpolate or cone search)
Also fixes #53
> Add neighbors method to high-level class

- CHANGES.rst
- astropy_healpix/bench.py
This now includes ang2pix, nest2ring and ring2nest. Results with OpenMP:
```
$ OMP_NUM_THREADS=4 python -m astropy_healpix.bench
Running benchmarks...
function  nest nside   size   time_healpy time_self   ratio 
--------- ----- ----- -------- ----------- ---------- -------
pix2ang  True     1       10   0.0000195  0.0006311   32.38
pix2ang  True   128       10   0.0000198  0.0005038   25.41
pix2ang  True     1     1000   0.0000767  0.0006432    8.38
pix2ang  True   128     1000   0.0000792  0.0005654    7.14
pix2ang  True     1  1000000   0.0649799  0.0659915    1.02
pix2ang  True   128  1000000   0.0645760  0.0913511    1.41
pix2ang  True     1 10000000   0.6714709  0.7274139    1.08
pix2ang  True   128 10000000   0.6703229  0.8520050    1.27
pix2ang False     1       10   0.0000263 …
```
> Expand benchmarks

- CHANGES.rst
- astropy_healpix/core.py
- astropy_healpix/tests/test_core.py
Healpy has an `nside2resol` function:
http://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.nside2resol.html
Both in Gammapy and the hips package we needed the reverse, a function that gives the closest nside or order for a given resolution.
* In Gammapy @woodmd implemented a `get_nside_from_pixel_size` function: https://github.com/gammapy/gammapy/blob/ae9067dad064aef16eb72e41cee425bf182b7229/gammapy/maps/hpx.py#L154
* In hipspy we added a `hips_order_for_pixel_resolution` function which is similar:
https://github.com/hipspy/hips/blob/2476251bea200d7221269b44772cb31660751730/hips/utils/healpix.py#L134
@astrofrog - Does it exist here already? Would it be welcome?
@astrofrog @woodmd - Can you recommend a signature? (i.e. return `nside` or `resolution`, but also if default should …
> Add resolution to order helper function

- astropy_healpix/conftest.py
- docs/healpy_compat.rst
Numpy's string representation of arrays changed significantly from 1.13 to 1.14. See the Numpy [changelog]. We have to set the legacy representation mode for our doctests to be reproducible across both old and new versions of Numpy.
[changelog]: https://docs.scipy.org/doc/numpy-1.14.0/release.html#many-changes-to-array-printing-disableable-with-the-new-legacy-printing-mode
> Make Numpy docstring output reproducible across Numpy versions

- docs/cone_search.rst
- docs/coordinates.rst
We return HEALPix indices as `np.int64`, which is the Numpy index type on 64-bit but not 32-bit platforms. On 32-bit platforms, Numpy will add `dtype=int64` to string representations of these arrays, which causes some doctests to fail.
This workaround calls `print()`, which always prints just the members of the array.
Fixes #81.
> Fix docstrings for 32 bit architectures

- astropy_healpix/healpy.py
In `get_interp_weights` for the `phi=None` case we forgot to pass `nside` along to the `pix2ang` call.
This PR fixes that issue; (still no test coverage of that line, I'd prefer to move on and improve test coverage later)
http://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.get_interp_weights.html
> Fix get_interp_weights for phi=None case

- astropy_healpix/healpy.py
- docs/conf.py
So far in the docs all intersphinx links to healpy were not working:
http://astropy-healpix.readthedocs.io/en/latest/api.html#module-astropy_healpix.healpy
This PR make it work.
> Fix docs intersphinx links to healpy

- cextern/.gitignore
- cextern/README.md
- cextern/astrometry.net/CuTest.c
- cextern/astrometry.net/CuTest.h
- cextern/astrometry.net/Makefile
- cextern/astrometry.net/example.c
- cextern/astrometry.net/healpix.h
- cextern/astrometry.net/test_healpix-main.c
- cextern/astrometry.net/test_healpix.c
It would be nice to polish `cextern/astrometry.net` a bit as a C library (remove things that aren't needed, add a README, maybe move the `interpolate.c` here as well?
The first thing I wanted to do was build it and run the tests:
```
$ cd cextern/astrometry.net
$ make
cc -o qsort_reentrant.o -c qsort_reentrant.c
make: *** No rule to make target `cutest.o', needed by `test_healpix'.  Stop.
```
@dstndstn @astrofrog - Is that https://github.com/asimjalis/cutest ?
Should we use it here or is there something better to test a C lib?
If we use cutest: how? Should we bundle a copy of the files?https://github.com/asimjalis/cutest#getting-started
> Fix make in  cextern/astrometry.net/Makefile

- astropy_healpix/tests/test_healpy.py
@lpsinger - https://github.com/astropy/astropy-healpix/issues/80 is not related to PPC, it is just a failure that happened to appear in that build. This PR adds that specific example to the hypothesis test and this fails for me locally on Mac. I don't have time to investigate why this is happening, so if anyone has any time please feel free to!
> Added failing example for test_pix2ang

- astropy_healpix/interpolation.c
- astropy_healpix/tests/test_core.py
- cextern/astrometry.net/healpix.c
Bilinear interpolation on invalid values (e.g. when calling
`reproject.reproject_from_healpix` where some values fall outside
the projection) should return NAN instead of printing to stderr
and raising an exception.
Before this patch, the [example in the docs for `ligo.skymap.plot.allsky`](https://lscsoft.docs.ligo.org/ligo.skymap/ligo/skymap/plot/allsky.html#example) was
failing with this output:
```
Invalid ring index: -537391105 4096
Invalid ring index: -537391105 4096
... repeated a few tens of thousands of times
Traceback (most recent call last):
File "./test.py", line 34, in <module>
ax.imshow_hpx(url, cmap='cylon')
File "/Users/lpsinger/src/ligo.skymap/venv/lib/python3.7/site-packages/ligo/skymap/plot/allsky.py", line 401, in imshow_hpx
nested=nested, field=field, smooth=smooth) …
```
> Fix bilinear interpolation of invalid values

- astropy_healpix/tests/test_healpy.py
I was looking at https://travis-ci.org/astropy/astropy-healpix/builds/425328133 for #105 and saw some fails. Actually I think they are unrelated to that PR and will show up for all PRs (cc @bmatthieu3 and @lpsinger)
E.g. `test_vec2ang` fails here:
https://travis-ci.org/astropy/astropy-healpix/jobs/425328140#L1119
And `test_uniq_to_levelipix` fails here:
https://travis-ci.org/astropy/astropy-healpix/jobs/425328145#L1220
And the style check build also fails here:
https://travis-ci.org/astropy/astropy-healpix/jobs/425328147#L860
@bmatthieu3 and @lpsinger - if you have time to fix those, please send a PR. Otherwise I can do it tomorrow evening.
> Test fails in master

- astropy_healpix/core.py
- astropy_healpix/tests/test_core.py
Following astropy/astropy-healpix#91 and astropy/regions#219 I moved the utils functions from MOCPy to here. These concern the translation of uniq number referring to a specific HEALPix cell to its order/pixel index.
I use the name `level` as a replacement for order because for the moment order refers to the HEALPix scheme used (ring, nested, XY).
So the methods added are `levelipix_to_uniq`, `uniq_to_levelipix` and I also added the methods `nside_to_level` and `level_to_nside` (the last one was already here but not accessible from the user API. I think it is useful to add it to the API because for example, with MOCPy we are more thinking in terms of level/order than nside and I usually do a nside=(1 << order) operation when instanciating a new HEALPix object in MOCPy. Having a function …
> Uniq to levelipix methods

- astropy_healpix/core_cython.pyx
- astropy_healpix/setup_package.py
- docs/performance.rst
This PR removes OpenMP from astropy-healpix.
This has been extensively discussed in #97 and #102 .
@astrofrog - I would suggest we merge this, and then release v0.3.
Note that currently our conda-corge build is broken on Python 3.7. I think that's an OpenMP related issue (mentioning threads), not a Cython issue, because you did make a release with a recent Cython after Python 3.7 was out.
https://github.com/conda-forge/astropy-healpix-feedstock/pull/7
@astrofrog - If you have time to make a release, great, please go ahead.
Otherwise I can also do it this week.
> Remove OpenMP from astropy-healpix

- astropy_healpix/high_level.py
- astropy_healpix/tests/test_high_level.py
- astropy_healpix/tests/test_utils.py
- astropy_healpix/utils.py
> Add HEALPix.from_header

- ah_bootstrap.py
- astropy_healpix/conftest.py
This is an automated update of the astropy-helpers submodule to v2.0.10. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v2.0.10/CHANGES.rst). 
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!* 
Similarly to the core package, the v3.0+ releases of astropy-helpers require Python 3.5+. We will open automated update PRs with astropy-helpers v3.2.x only for packages that specifically opt in for it when they start supporting Python 3.5+ only. Please let @bsipocz or @astrofrog know or add your …
> Update astropy-helpers to v2.0.10

- astropy_healpix/_core.c
- astropy_healpix/core.py
- astropy_healpix/healpy.py
The core Astrometry.net implementations of lonlat_to_healpix and healpix_to_lonlat do conversion between spherical coordinates and Cartesian coordinates. If the user wants Cartesian coordinates, then we can save some trigonemetric function evaluations by providing functions that natively speak Cartesian coordinates.
> Add core wrappers for healpix_to_xyz and xyz_to_healpix

- astropy_healpix/tests/test_healpy.py
The following unit test failures on i386 were discovered by the Debian reproducible builds project (https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/astropy-healpix.html):
```
=================================== FAILURES ===================================
__________________________ test_nside2pixarea[2-True] __________________________
nside = 2, degrees = True
@pytest.mark.parametrize(('nside', 'degrees'), product(NSIDE_VALUES, (False, True)))
def test_nside2pixarea(nside, degrees):
actual = hp_compat.nside2pixarea(nside=nside, degrees=degrees)
expected = hp.nside2pixarea(nside=nside, degrees=degrees)
>       assert_equal(actual, expected)
E       AssertionError:
E       Items are not equal:
E        ACTUAL: 859.43669269623479
E        DESIRED: 859.43669269623467 …
```
> Fix floating point unit test failures on i386

- astropy_healpix/_astropy_init.py
This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
> MNT: Remove unused astropy config code 

- astropy_healpix/core.py
This PR removes the old and unused `_restore_shape` and `_validate_healpix_index` helper functions. I just noticed them in the code coverage report.
There is the question if we should validate `healpix_index` or not, and if it's not in the range what to do. (the `_restore_shape` just isn't needed any more since @lpsinger introduced ufuncs)
Currently the check is here:
https://github.com/astropy/astropy-healpix/commit/87bf0c1990825f51ac4fa5a289461b50608ddcd0#diff-d16b2ef86578243bf558a029cbcd7fdeR33
and what we get is `NaN` in the output and a RunTimeWarning:
```
In [5]: astropy_healpix.healpix_to_lonlat(99, 1) …
```
> Remove old unused helper functions

- .gitignore
This brings in gitignores for VS Code project directories, among other things.
> Update gitignore from Astropy package template

- astropy_healpix/core.py
There is really no reason for it not to be exported. I was looking for it in order to plot boundaries of a set of HEALPix tiles of mixed resolutions, and was surprised to find that I had to directly import it from `astropy_healpix.core`.
> Export boundaries_lonlat in __all__

- CHANGES.rst
- azure-pipelines.yml
- docs/installation.rst
- environment-dev.yml
- setup.cfg
Python 3.6 is apparently no longer supported. That's fine, because 3.6 hits end of life in a few weeks.
> Disable Azure pipelines for Python 3.6

- astropy_healpix/conftest.py
- astropy_healpix/setup_package.py
- setup.cfg
This pull request is to remove soon to be deprecated code; also see astropy/astropy#12633 . Also stop using `distutils` and officially set minversion for `astropy`.
> MNT: Stop using deprecated astropy.tests functions

- .github/workflows/publish.yml
- pyproject.toml
Should also fix this error:
```
The workflow is not valid. .github/workflows/publish.yml (Line: 13, Col: 5): Unexpected value 'env'
```
> Move cibuildwheel setup to pyproject.toml

- .github/workflows/ci_tests.yml
- astropy_healpix/_core.c
Since gcc 10 is no longer supported (https://gcc.gnu.org/gcc-10/), and this workaround is causing issues with packaging on conda-forge (https://github.com/conda-forge/astropy-healpix-feedstock/pull/32), remove the workaround.
I had to bump the Ubuntu version in the oldestdeps test to pick up a newer version of gcc (gcc-9 > gcc-11)
> Remove old placeholder workaround

- astropy_healpix/_core.c
See https://github.com/numpy/numpy/pull/15355.
CC @dstansby.
> Make Numpy loop function args const correct

- astropy_healpix/setup_package.py
- pyproject.toml
Allow using any version of Numpy between 1.25 and 2. This will allow us to use the latest release of Numpy on PyPI and take advantage of prebuilt wheels for more platforms and architectures.
Use the new `NPY_TARGET_VERSION` macro to peform a backward-compatible supporting versions of Numpy as old as 1.19.
> Unpin Numpy version for building wheels

- .github/workflows/publish.yml
- pyproject.toml
We need to release new wheels of reproject compiled against Numpy 2.0.0rc1 ahead of the final Numpy 2.0.0 release, so this PR updates the build-time dependencies and also simplifies the nightly wheels configuration.
> Build against Numpy 2.0.0rc1 or later

- astropy_healpix/core.py
Unblocks #214
This isn't the only place where `copy=False` is used in the code base, but that's the only one that causes tests to fail, looking at [example logs](https://github.com/astropy/astropy-healpix/actions/runs/8568206064/job/23481585092?pr=214), so the fix is minimal. If other call sites with `copy=False` raise errors with numpy 2.0 in the future they could be adjusted similarly.
> BUG: fix compatibility with numpy 2.0.0 (copy semantics)

- pyproject.toml
PyPy is probably not long for this world; see
https://github.com/mesonbuild/meson-python/pull/626#issuecomment-2111018667.
Fixes #216.
> Don't build wheels for PyPy

- astropy_healpix/core.py
- astropy_healpix/high_level.py
Some HEALPix pixels do not have all 8 neighbours. In these cases, the corresponding entry in the returned array has the value of -1 and Numpy may print an invalid value warning. To suppress the warning, use `numpy.errstate`.
Fixes #217.
> Document that neighbours function may return -1

- .github/workflows/ci_cron_weekly.yml
- .github/workflows/ci_tests.yml
- .github/workflows/publish.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- .readthedocs.yml
See https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Add sphinx.configuration variable to fix Sphinx build

- astropy_healpix/tests/test_healpy.py
These tests are failing on MIPS where the timings seem to be quite unreliable.
Ported from https://salsa.debian.org/debian-astro-team/astropy-healpix/-/blob/master/debian/patches/0002-Disable-deadline-for-some-flaky-tests.patch?ref_type=heads.
> Disable deadline for some flaky tests

- tox.ini
It is still used in the GH Actions workflow.
> Add back predeps tox env

- .github/workflows/ci_tests.yml
- astropy_healpix/tests/test_healpy.py
- tox.ini
- Fix test_vec2ang near poles. Compare the angular separation between the desired and actual coordinates rather than the coordinates themselves to avoid comparing meaningless values of longitude near the poles.
- Fix test_vec2pix near pixel boundaries. Don't test the return value on pixel boundaries; here, ipix is ambiguous.
- Add healpy to test dependencies so that test_healpy is run in the GitHub Actions pipeline.
Fixes #183.
> Fix broken unit tests in test_healpy

- astropy_healpix/_core.c
- astropy_healpix/tests/test_core.py
This is found to fix abort errors that occurred on macOS x86_64 when running the unit tests for the Conda packages. See https://github.com/conda-forge/astropy-healpix-feedstock/pull/41.
This might indicate that some of the Conda builds have assertions disabled via the `NDEBUG` preprocessor macro, and some have them enabled, inconsistently.
Without this patch, any number of assertions should have been tripped. For example, this one:
https://github.com/astropy/astropy-healpix/blob/v1.1.1/cextern/astrometry.net/healpix.c#L742
> Check interpolate_bilinear_lonlat inputs for invalid values

- astropy_healpix/utils.py
- pyproject.toml
> Treat warnings in unit tests as errors
