astropy/astropy-healpix

Makefile, healpix/raw/example.c, healpix/raw/example.h, healpix/raw/setup_package.py
I'm setting up this new `healpix` repo that's supposed to contain a C library wrapped with Cython and built using astropy-helpers.
Here's what I tried:
https://github.com/cdeil/healpix/tree/master/healpix/raw
But I'm getting this error:
```
$ python setup.py test -V
running test
running build
running build_py
copying healpix/version.py -> build/lib.macosx-10.11-x86_64-3.5/healpix
copying healpix/raw/wrap.c -> build/lib.macosx-10.11-x86_64-3.5/healpix/raw
running build_ext
skipping 'healpix/raw/wrap.c' Cython extension (up-to-date)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/utils/introspection.py:153: UserWarning: Module healpix was already imported from /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/healpix-test-kd3w3l71/lib.ma …
```
=> Cython build error

.travis.yml, docs/installation.rst, setup.cfg
@bsipicz @astrofrog - I'm getting this Sphinx error from astropy-helpers for the new `healpix` package I set up today:
https://travis-ci.org/cdeil/healpix/jobs/157661206#L605
Help!?
=> Sphinx build fail on travis-ci

cextern/astrometry.net/healpix-utils.c, cextern/astrometry.net/healpix-utils.h, cextern/astrometry.net/healpix.c, cextern/astrometry.net/healpix.h, cextern/astrometry.net/starutil.h, cextern/astrometry.net/test_healpix.c, healpix/core.py, healpix/core_cython.pxd, healpix/core_cython.pyx, healpix/tests/test_core_cython.py
This adds the Cython wrapper for the cone search
=> Implement cone search wrapper

.run_docker_tests.sh, appveyor.yml, cextern/astrometry.net/healpix.h, docs/conf.py, docs/using.rst, healpix/core.py, healpix/core_cython.pyx, healpix/high_level.py, healpix/tests/test_core.py, healpix/tests/test_core_cython.py, healpix/tests/test_high_level.py
Includes some other improvements to the docs
=> Python interface for cone search

docs/using.rst, healpix/core.py, healpix/high_level.py, healpix/tests/test_core.py, healpix/tests/test_high_level.py
Includes the high-level interface
=> Functionality to return boundary position of pixels

healpix/core.py, healpix/healpy.py, healpix/tests/test_core.py, healpix/tests/test_healpy.py
=> Implement level_to_nside

.travis.yml, cextern/astrometry.net/healpix-utils.c, cextern/astrometry.net/healpix.c, cextern/astrometry.net/healpix.h, healpix/core.py, healpix/core_cython.pyx, healpix/healpy.py, healpix/high_level.py, healpix/tests/test_core.py, healpix/tests/test_healpy.py
This improves the healpy compatibility interface and also adds hypothesis for testing healpy vs healpix.healpy
Fixes #1
=> Various improvements

cextern/astrometry.net/healpix.c, healpix/tests/test_healpy.py
=> Fix remaining precision issues

.travis.yml
This removes Python 3.4 and adds 3.6
=> Travis: update Python versions

.travis.yml, docs/boundaries.rst, docs/installation.rst, healpix/core.py, healpix/healpy.py, healpix/tests/test_healpy.py
@cdeil - does this work for you?
=> Added boundaries healpy compat function

astropy_healpix/interpolation.h
Signed-off-by: James Noss <jnoss@stsci.edu>
=> Add header guard to interpolation.h

cextern/astrometry.net/bl-nl.c, cextern/astrometry.net/bl.c, cextern/astrometry.net/healpix-utils.c, cextern/astrometry.net/healpix.c, cextern/astrometry.net/mathutil.c, cextern/astrometry.net/permutedsort.c
The C code had some weird mix of 8 and 4 spaces.  This change only affects whitespace.
=> reindent to four spaces

cextern/astrometry.net/healpix.c
as suggested by @mreineck in https://github.com/astropy/astropy-healpix/pull/93#issuecomment-400416163
=> use more stable cos(Dec) term

cextern/astrometry.net/healpix-utils.c
Fix casts and eliminate a memory leak.
=> Healpix rangesearch cleanup

cextern/astrometry.net/LICENSE
Sorry @dstndstn - I could have sworn I had done this!
Fixes https://github.com/astropy/astropy-healpix/issues/136
=> Added astrometry.net LICENSE

azure-pipelines.yml, tox.ini
@lpsinger - just doing this to build Python 3.9 wheels then I'll do the release, sorry for the delay!
=> Added Python 3.9 to CI

docs/interpolation.rst
=> Fix flipped image in interpolation example

CHANGES.rst, astropy_healpix/high_level.py
Signed-off-by: nstarman <nstarkman@protonmail.com>
Fixes #161
=> HEALPix class checks the 'order' argument

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_tests.yml, .github/workflows/publish.yml, README.rst, tox.ini
=> TST: Fix CI and badges

setup.cfg
=> Unpin hypothesis

.github/workflows/ci_tests.yml, tox.ini
=> Test based on pre-release deps

docs/index.rst
=> Remove API stability warning

.readthedocs.yml
=> Remove obsolete RTD system_packages directive

.github/workflows/publish.yml
=> Build developer wheels against Numpy dev

astropy_healpix/healpy.py, astropy_healpix/high_level.py
See https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
=> Fix test failures with Numpy 2.x due changes in copy kwarg

.github/workflows/publish.yml, pyproject.toml
Not sure if this helps or not but better be explicit than implicit?
=> BLD: More explicit architectures for Linux x86

.github/workflows/publish.yml, pyproject.toml
Not sure if this helps or not but better be explicit than implicit?
=> BLD: More explicit architectures for Windows and OSX

astropy_healpix/tests/test_utils.py
Saw a failure about this in https://github.com/astropy/astropy/pull/17861
=> TST: Replace tmpdir with tmp_path and minor clean-up
